refactor, not tested

diff --git a/ParseParams b/ParseParams
--- a/ParseParams
+++ b/ParseParams
@@ -1,17 +1,22 @@
 #!/bin/bash
 
-source utility
+#source utility
+source ./tools
 
 #############################################################################
 # Are we being sourced?
 
-[[ ${BASH_SOURCE[0]} == "$0" ]] && die "$(basename "$0") must only be sourced."
+#[[ ${BASH_SOURCE[0]} == "$0" ]] && die "$(basename "$0") must only be sourced."
+sourced || die 'ParseParams must only be sourced'
 
 #----------------------------------------------------------------------------
 # Check version of getopt.
 
 getopt -T &> /dev/null
-[[ $? -ne 4 ]] && die "Unsupported version of getopt!"
+[[ $? -eq 4 ]] || die "Unsupported version of getopt!"
+
+# Turn on extended globbing
+shopt -s extglob
 
 #############################################################################
 # Documentation
@@ -30,7 +35,7 @@ ParseParams - Parse command line or function parameters.
   b|bank,number,BankNumber
   c,boolean
   '
-  parse_params "$PARM_DEF" "$@" || show_usage
+  parse_params "\$PARM_DEF" "\$@" || show_usage
 
 =head1 OPTIONS
 
@@ -41,7 +46,7 @@ The first parameter is the parameter definition string, described below.
 
 The remaining parameters are the input parameters to be validated.
 
-NOTE: Not explicitly including "$@" is allowed but this scenario has not been
+NOTE: Not explicitly including "\$@" is allowed but this scenario has not been
 tested.
 
 =head1 DESCRIPTION
@@ -178,7 +183,10 @@ either a 0 (true) if it does, or 1 (false) if not.
 =cut
 POD
 
-# is_varname is managed in the _build_parms and _build_eval_string functions.
+valid_varname() {
+  var_rx='[_[:alpha:]]*([_[:alnum:]])'
+  [[ $1 =~ ^$var_rx$ ]]
+}
 
 #############################################################################
 # Main function
@@ -284,9 +292,6 @@ function parse_params() {
   local -a POS_LINES
   local ERR=0
 
-  # work around bash stripping trailing newlines in process sustitution
-  printf -v CRLF '\n'
-
   _build_parms_info "$1"
   shift
 
@@ -354,8 +359,11 @@ POD
 function _build_parms_info() {
   [[ -z $1 ]] && die 'No definitions were passed to _build_parms_info.'
 
-  local OPT VAR DEFAULT
+  local OPTION VAR DEFAULT
   local -l TYPE REQ
+
+  # Is this a positional definition?
+  local POS_DEF='#' # If you change this make sure you update the documentation!
 
   IFS=$'\n' readarray -t def_lines <<< "$1"
 
@@ -363,101 +371,81 @@ function _build_parms_info() {
     [[ -z ${def_lines[BPI_IX]} ]] && continue
 
     line="${def_lines[BPI_IX]}"
-
     debug "line $BPI_IX: $line"
 
-    IFS=', ' read -r OPT TYPE VAR DEFAULT REQ <<< "$line"
+    IFS=', ' read -r OPTION TYPE VAR DEFAULT REQ <<< "$line"
+    #debug "OPTION: $OPTION ::: TYPE: $TYPE ::: VAR: $VAR ::: DEFAULT: $DEFAULT ::: REQ: $REQ <"
 
-    #debug "OPT: $OPT ::: TYPE: $TYPE ::: REQ: $REQ ::: VAR: $VAR ::: DEFAULT: $DEFAULT <"
+    #------------------------------------------------------------------------
+    [[ -z $REQ ]] && REQ='optional'
 
+    [[ $REQ =~ required|optional ]] || {
+      warn "Unknown field value ($REQ) on line $BPI_IX (only 'required', 'optional' or null is valid)."
+      ((ERR++))
+      continue
+    }
+
+    #------------------------------------------------------------------------
     [[ " ${TYPES[*]} " == *" $TYPE "* ]] || {
       warn "Unknown type ($TYPE) on line $BPI_IX ($line)."
       ((ERR++))
+      continue
     }
 
-    # Is this a positional definition?
-    POS_DEF='#' # If you change this make sure you update the documentation!
+    [[ $TYPE == 'boolean' ]] && REQ='optional'
 
-    if [[ $OPT == "$POS_DEF" ]]; then
-      is_varname "$VAR" || {
-        warn "Invalid variable name (${VAR:-required for positional parameter}) on line $BPI_IX ($line)."
-        ((ERR++))
-      }
+    #------------------------------------------------------------------------
+    [[ -z $VAR ]] && {
+      warn "Variable name is required on line $BPI_IX ($line)."
+      ((ERR++))
+      continue
+    }
 
+    valid_varname "$VAR" || {
+      warn "Invalid variable name ($VAR) on line $BPI_IX ($line)."
+      ((ERR++))
+      continue
+    }
+
+    #------------------------------------------------------------------------
+    if [[ $subopt == "$POS_DEF" ]]; then
       POS_LINES+=("$TYPE,$VAR")
+      continue
+    fi
 
-    else
-      [[ -z $REQ ]] && REQ='optional'
+    local -a subopts
+    IFS='|' read -ra subopts <<< "$OPTION"
 
-      REQ="${REQ,,}"
-
-      [[ $REQ =~ required|optional ]] || {
-        warn "Unknown field value ($REQ) on line $BPI_IX."
-        ((ERR++))
-      }
-
-      [[ $TYPE == 'boolean' ]] && REQ='optional'
-
-      TEMPVAR="$OPT"
-
-      if is_char "$OPT"; then
-        [[ $SHORTOPTS == *"$OPT"* ]] && {
-          warn "Repeated short option ($OPT) on line $BPI_IX."
+    for subopt in "${subopts[@]}"; do
+      if [[ $subopt =~ ^[[:alnum:]]$ ]]; then
+        [[ $SHORTOPTS == *"$subopt"* ]] && {
+          warn "Repeated short option ($subopt) on line $BPI_IX."
           ((ERR++))
+          continue
         }
 
-        SHORTOPTS+="$OPT"
+        SHORTOPTS+="$subopt"
         [[ $TYPE != 'boolean' ]] && SHORTOPTS+=':'
 
-      elif [[ $OPT != *"|"* ]]; then
-        [[ $LONGOPTS == *"$OPT"* ]] && {
-          warn "Repeated long option ($OPT) on line $BPI_IX."
+      elif [[ $subopt =~ ^[[:alnum:]]+$ ]]; then
+        [[ $LONGOPTS == *"$subopt"* ]] && {
+          warn "Repeated long option ($subopt) on line $BPI_IX."
           ((ERR++))
+          continue
         }
 
-        LONGOPTS+="$OPT"
+        LONGOPTS+="$subopt"
         [[ $TYPE != 'boolean' ]] && LONGOPTS+=':,'
+
       else
-        TMP_SHORTOPT="${OPT%|*}"
-
-        [[ $SHORTOPTS == *"$TMP_SHORTOPT"* ]] && {
-          warn "Repeated short option ($OPT) on line $BPI_IX."
-          ((ERR++))
-        }
-
-        SHORTOPTS+="$TMP_SHORTOPT"
-
-        TMP_LONGOPT="${OPT##*|}"
-
-        [[ $LONGOPTS == *"$TMP_LONGOPT"* ]] && {
-          warn "Repeated long option ($OPT) on line $BPI_IX."
-          ((ERR++))
-        }
-
-        LONGOPTS+="$TMP_LONGOPT"
-
-        TEMPVAR="${OPT##*|}"
-
-        if [[ $TYPE != 'boolean' ]]; then
-          SHORTOPTS+=':'
-          LONGOPTS+=':'
-        fi
-
-        LONGOPTS+=','
-      fi
-
-      [[ -z $VAR ]] && VAR=$TEMPVAR
-
-      is_varname "$VAR" || {
-        warn "Invalid variable name ($VAR) on line $BPI_IX ($line)."
+        warn "Invalid suboption ($subopt) on line $BPI_IX."
         ((ERR++))
-      }
+      fi
+    done
 
-      DEF_LINES+=$(printf '%s,' "$OPT" "$TYPE" "$VAR" "$DEFAULT" "$REQ")
-      DEF_LINES="${DEF_LINES%%,}"
-      DEF_LINES+="$CRLF"
-
-    fi
+    DEF_LINES+=$(printf '%s,' "$OPTION" "$TYPE" "$VAR" "$DEFAULT" "$REQ")
+    DEF_LINES="${DEF_LINES%%,}"
+    DEF_LINES+=$'\n'
   done
 
   # Get rid of trailing ','
@@ -467,24 +455,8 @@ function _build_parms_info() {
   debug "POS_LINES: ${POS_LINES[*]} <"
   debug "$(printf '%-15s - %-15s <' 'SHORTOPTS' 'LONGOPTS')"
   debug "$(printf '%-15s - %-15s <' "$SHORTOPTS" "$LONGOPTS")"
-  debug "ERR: $ERR"
 
   ((ERR)) && {
-    #    DEBUG=1
-    #    debug 'Matches?'
-    #    # shellcheck disable=SC2034
-    #    DEBUG=0
-
-    #    for IX in "${!BASH_SOURCE[@]}"; do
-    #      bs+="$(printf '|%20s' "$(basename "${BASH_SOURCE[IX]}")")"
-    #      fn+="$(printf '|%20s' "${FUNCNAME[IX]}")"
-    #      ln+="$(printf '|%20s' "${BASH_LINENO[IX-1]?$LINENO}")"
-    #    done
-
-    #    warn "bs: $bs"
-    #    warn "fn: $fn"
-    #    warn "ln: $ln"
-
     bs="$(basename "${BASH_SOURCE[2]}:")"
     fn="${FUNCNAME[2]}:"
     [[ $fn =~ main:|source: ]] && fn=
@@ -492,7 +464,6 @@ function _build_parms_info() {
 
     die "Problems with options definition at $bs$fn$ln, exiting."
   }
-
 }
 
 #----------------------------------------------------------------------------
@@ -515,7 +486,9 @@ function _build_eval_string() {
     die "Either DEF_LINES or POS_LINES needs to be set."
   fi
 
-  local DEFAULTS_STRING REQUIRED_STRING
+  local OPTION VAR DEFAULT DEFAULTS_STRING REQUIRED_STRING CASE_STRING
+  local -l TYPE REQ
+  local CRLF=$'\n'
 
   IFS=$'\n' readarray -t def_lines <<< "$DEF_LINES"
 
@@ -524,37 +497,31 @@ function _build_eval_string() {
 
     debug "line $BES_IX: $(printf '%s' "${def_lines[BES_IX]}")"
 
-    IFS=',' read -r OPT TYPE VAR DEFAULT REQ <<< "${def_lines[BES_IX]}"
-
-    #debug "OPT: $OPT ::: TYPE: $TYPE ::: REQ: $REQ ::: VAR: $VAR ::: DEFAULT: $DEFAULT <"
+    IFS=',' read -r OPTION TYPE VAR DEFAULT REQ <<< "${def_lines[BES_IX]}"
+    #debug "OPTION: $OPTION ::: TYPE: $TYPE ::: VAR: $VAR ::: DEFAULT: $DEFAULT ::: REQ: $REQ <"
 
     CASE_STRING+="$CRLF"
 
-    if is_char "$OPT"; then
-      CASE_STRING+="-$OPT)$CRLF"
-    elif [[ $OPT != *"|"* ]]; then
-      CASE_STRING+="--$OPT)$CRLF"
+    if [[ $OPTION =~ ^[[:alnum:]]$ ]]; then
+      CASE_STRING+="-$OPTION)$CRLF"
+    elif [[ $OPTION != *"|"* ]]; then
+      CASE_STRING+="--$OPTION)$CRLF"
     else
-      CASE_STRING+="-${OPT/|/ | \-\-})$CRLF"
+      CASE_STRING+="-${OPTION/|/ | \-\-})$CRLF"
     fi
 
-    CASE_STRING+="debug \"case: $OPT \$(printf '%s' \$2)\"$CRLF"
+    CASE_STRING+="debug \"case: $OPTION \$(printf '%s' \$2)\"$CRLF"
 
     if [[ $TYPE == 'boolean' ]]; then
       CASE_STRING+="$VAR=0$CRLF"
       CASE_STRING+="shift$CRLF"
 
       DEFAULT=1
-    elif [[ $TYPE == 'filename' ]]; then
-      CASE_STRING+="$VAR=\"\$(qualify_filename \"\$2\")\" || die \"Invalid filename (\$2)\"$CRLF"
-      CASE_STRING+="shift 2$CRLF"
-
-      [[ -n $DEFAULT ]] && DEFAULT="$(qualify_filename "$DEFAULT")"
     else
       CASE_STRING+="$VAR=\"\$2\"$CRLF"
       CASE_STRING+="shift 2$CRLF"
 
-      VALIDATE_STRING+="_check_type '$VAR' '$TYPE' || { warn \"$OPT (\$$VAR) is not a $TYPE.\"; ((ERR++)); }$CRLF"
+      VALIDATE_STRING+="_check_type '$VAR' '$TYPE' || { warn \"$OPTION (\$$VAR) is not a $TYPE.\"; ((ERR++)); }$CRLF"
     fi
 
     CASE_STRING+=";;$CRLF"
@@ -564,7 +531,7 @@ function _build_eval_string() {
     fi
 
     if [[ $REQ == 'required' ]]; then
-      REQUIRED_STRING+="[[ -n \$$VAR ]] || { warn '$VAR ($OPT) is required.'; ((ERR++)); }$CRLF"
+      REQUIRED_STRING+="[[ -n \$$VAR ]] || { warn '$VAR ($OPTION) is required.'; ((ERR++)); }$CRLF"
     fi
 
     DEBUG_STRING+="debug \"(after case) $VAR: \$$VAR\"$CRLF"
@@ -616,12 +583,13 @@ $CASE_STRING
 "
   fi
 
-  if [[ "${#POS_LINES[@]}" -gt 0 ]]; then
+  # This eval will execute arbitrary code from the command line. Don't use it!
+  #[[ -n \$1 ]] && eval \"\$VAR=\$1\"
+
+  if [[ ${#POS_LINES[@]} -gt 0 ]]; then
     POS_STRING="
   for PL_IX in \"\${!POS_LINES[@]}\"; do
     IFS=',' read -r TYPE VAR <<< \"\${POS_LINES[PL_IX]}\"
-    # This eval will execute arbitrary code from the command line. Don't use it!
-    #[[ -n \$1 ]] && eval \"\$VAR=\$1\"
     [[ -n \$1 ]] && IFS= read -r \"\$VAR\" <<< \"\$1\"
     debug \"(in pos loop) \$VAR: \${!VAR}\"
     _check_type \"\$VAR\" \"\$TYPE\" || { warn \"'\${!VAR}' (position \$PL_IX) is not a \$TYPE\"; ((ERR++)); }
@@ -645,8 +613,6 @@ $VALIDATE_STRING
 }
 "
 
-  #debug "$(echo "$EVAL_STRING" | shfmt -s -i 2 -bn -ci -sr | cat -n)"
   debug "$(echo "$EVAL_STRING" | shfmt -s -i 2 -bn -ci -sr)"
-
   printf '%s' "$EVAL_STRING"
 }
